spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${PG_DATABASE}
    username: ${PG_USERNAME:}
    password: ${PG_PASSWORD:}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.ailang: info
